[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"
